SELECT PC.PRODUCT_ID, PD.PRODUCT_NAME , PD.SHORT_NAME, PC.PRICE_ID, PC.PRICE_NOT_VAT, PC.PRICE , PC.PACKAGE_PRICE_NOT_VAT, PC.PACKAGE_PRICE, PC.VAT
from PRICE as PC
INNER JOIN PRODUCT as PD
ON PC.PRODUCT_ID = PD.PRODUCT_ID
where PC.SHOP_ID = 2
ORDER by PC.PRODUCT_ID
