SELECT   PARENT_AREA_ID, AREA_ID, PROVINCE, PROVINCE_NAME, DISTRICT, DISTRICT_NAME as DISTRICT_WITH_BIGGEST_AREA_CODE,  AREA_NAME, Max(AREA_CODE)  as AREA_CODE
from AREA
WHERE 
PROVINCE in 
(SELECT PROVINCE 
FROM AREA 
where PARENT_AREA_ID = 2)
and PRECINCT_NAME is NULL and DISTRICT_NAME is not NULL
GROUP by PROVINCE_NAME 
ORDER by PARENT_AREA_ID;